if $SHELL =~ 'bin/fish'
    set shell=/bin/sh
endif

set nocompatible
let g:ale_completion_enabled = 1

call plug#begin('~/.nvim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'ecomba/vim-ruby-refactoring'
Plug 'editorconfig/editorconfig-vim'
Plug 'elzr/vim-json'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/gv.vim'
Plug 'junegunn/vim-easy-align'
Plug 'kassio/neoterm'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
Plug 'scrooloose/nerdtree'
Plug 'shime/vim-livedown'
Plug 'tmhedberg/matchit'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-rails'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-erlang/vim-erlang-runtime'
Plug 'vim-erlang/vim-erlang-compiler'
Plug 'vim-erlang/vim-erlang-omnicomplete'
Plug 'wakatime/vim-wakatime'
Plug 'w0rp/ale'
call plug#end()

let $NVIM_TUI_ENABLE_TRUE_COLOR=1

set encoding=utf8
set regexpengine=1
set nobackup
set nowb
set noswapfile
set vb
syntax enable
set t_Co=256
set background=dark
colorscheme Tomorrow-Night
try
    set undodir=~/.vim/undodir
        set undofile
    catch
endtry
set hidden
set cf
set history=256
set nu
set nowrap
set timeoutlen=250
set nocursorline
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set cindent
set autoindent
set bs=2
set nocp incsearch
set colorcolumn=80
set formatoptions=tcqr
set backspace=indent,eol,start
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set mat=5
set list listchars=tab:»·,trail:·
set cmdheight=1
set noshowmode
set laststatus=2
set completeopt-=preview
set mousehide
set mouse=a
filetype plugin on

if has('conceal')
  set conceallevel=2 concealcursor=i
endif

function! SaveProper()
    let current_filetype = &filetype
    if (index(s:tab_sensitive_filetypes, current_filetype) < 0)
        :%s/\s\+$//e " delete trailing whitespace
        :set et| retab " change indent to spaces and retab
    endif
    :set ff=unix " set line endings to unix
    :update " write to disk
endfunction

function! GitSearch()
    let query = input('Search for: ')
    :call GitSearchForWord(query)
endfunction

function! GitSearchForWord(query)
    if !empty(a:query)
        execute ":Ag " . a:query
    endif
endfunction

" Use bc to evaluate arithmetic expressions
function! CalculateExpression(expr)
    if !empty(a:expr)
        return system("echo 'print " . a:expr . "' | bc -l")
    endif
endfunction

function! GetVisual() range
    let reg_save = getreg('"')
    let regtype_save = getregtype('"')
    let cb_save = &clipboard
    set clipboard&
    normal! ""gvy
    let selection = getreg('"')
    call setreg('"', reg_save, regtype_save)
    let &clipboard = cb_save
    return selection
endfunction

function! FormatJsonFunction()
    :%!python -m json.tool
endfunction

:command! FormatJson :call FormatJsonFunction()<CR>

function! CopyMatches()
    let hits = []
    %s//\=len(add(hits, submatch(0))) ? submatch(0) : ''/ge
    let reg = '"'
    execute 'let @'.reg.' = join(hits, "\n") . "\n"'
endfunction

:command! YankMatches :call CopyMatches()<CR>

augroup vimrc_autocmd
    autocmd!
    autocmd BufRead,BufNewFile *.js.erb set filetype=javascript
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType php setlocal omnifunc=javascriptcomplete#CompletePHP
    "autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
    "autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
    "autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
    "autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
    autocmd FileType ruby setlocal re=1 foldmethod=manual
    autocmd FileType make set noexpandtab
    autocmd Syntax * call matchadd('Todo',  '\W\zs\(TODO\|FIXME\|CHANGED\|XXX\|BUG\|HACK\)')
    " autocmd! BufWritePost * Neomake
augroup END
let s:tab_sensitive_filetypes = ['make']

set wildignore+=*.psd,*.doc,*.docx,*.xlsx
set wildignore+=*/vendor/**
set wildignore+=*/node_modules/**
set wildignore+=*/bower_components/**

let mapleader = ","
inoremap jk <esc>
nnoremap <space>is :call GitSearch()<cr>
nnoremap <space>s :Ag <C-R><C-W><cr>
vnoremap <space>s :call GitSearchForWord(GetVisual())<CR>
nnoremap <silent> <C-s> :call SaveProper()<CR>
nnoremap <space> :noh<cr>
nnoremap <leader>n :NERDTreeToggle<cr>
nnoremap <leader>z :TlistToggle<cr>
nnoremap <leader>N :NERDTreeFind<cr>
nnoremap <leader>s :silent! make<CR>
nnoremap <C-tab> :bn<CR>
nnoremap <C-S-tab> :bp<CR>
inoremap <C-tab> <Esc>:bn<CR>i
inoremap <C-S-tab> <Esc>:bp<CR>i
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
tnoremap <C-j> <c-\><c-n><c-w>j
tnoremap <C-k> <c-\><c-n><c-w>k
tnoremap <C-h> <c-\><c-n><c-w>h
tnoremap <C-l> <c-\><c-n><c-w>l
au WinEnter *pid:* call feedkeys('i')
nmap gV `[v`] "highlight last inserted text
nnoremap <leader>x :bp<bar>sp<bar>bn<bar>bd<CR> " close current buffer without closing the window
nnoremap <leader>c :clo<CR> " close current window
nnoremap <leader>v :vs<CR> " vertical split
nnoremap <leader>h :vertical resize -5<cr>
nnoremap <leader>l :vertical resize +5<cr>
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gw :Gwrite<cr>
nnoremap <leader>gc :GCommit<cr>
nnoremap <leader>gp :Gpush<cr>
nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
imap <c-l> <space>=><space>
imap <c-b> ->
imap <C-c> <CR><Esc>O
imap <C-e> <Esc>A
nnoremap Q :qa<CR>
noremap q: <nop>
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
nnoremap <C-P> :Files<CR>
noremap <C-A> :Buffers<CR>
noremap <Leader>f g<C-]>
vnoremap // y/<C-R>"<CR>

" terminal keybinds
nnoremap <silent> <Leader>t  :Tnew<cr>
nnoremap <silent> <Leader>r  :T dew rails c
nnoremap <silent> <Leader>e :TREPLSendLine<cr>
vnoremap <silent> <Leader>e :TREPLSendSelection<cr>
nnoremap <silent> ,th :call neoterm#close()<cr>

" use for arithmetic expressions, selection will be replaced with it's value
vnoremap <space>e :s/\%V.*/\=CalculateExpression(submatch(0))/<CR>:noh<CR>

let g:ale_linters_explicit = 1 " run only the linters defined explictly below
let g:ale_linters = {
\   'ruby': ['rubocop', 'reek'],
\}

" Use K for show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if &filetype == 'vim'
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

let NERDTreeShowHidden=1

let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_powerline_fonts = 0
let g:airline_theme='tomorrow'
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#ale#enabled = 1

let g:mta_filetypes = { 'html' : 1, 'xhtml' : 1, 'xml' : 1, 'jinja' : 1, 'eruby' : 1, 'twig' : 1, 'erb'  : 1, }

let g:vim_json_syntax_conceal = 0
let g:neoterm_shell='fish'
let g:neoterm_default_mod = 'horizontal'
let g:neoterm_keep_term_open = 0
let g:neoterm_autoinsert = 1

let g:livedown_autorun = 1
